include:
  - local: '/common/.gitlab-ci.yml'
  - local: '/readme/.migration-guide.gitlab.yml'
  - local: '/secret-scanning/.gitlab-ci.yml'
  - local: '/release/.gitlab-ci.yml'

variables:
  RELEASE_VERSION: 1.0.0
  LINT_YAML_FILES: "**/.gitlab-ci.yml"
  LINT_MD_FILES: "*.md"

  WORKFLOW:
    value: "full-pipeline"
    options:
      - "full-pipeline"
      - "check"
      - "lint"
      - "secret-scanning"
    description: "Select the workflow to execute. (Active during manual Web / API runs)"

YAML:Lint:
  extends:
    - .YAML:Lint
    - .lint-workflow-rules

MD:Lint:
  extends:
    - .MD:Lint
    - .lint-workflow-rules
  needs:
    - job: Common:Init
      artifacts: false
      optional: true

Trivy:Cache:Warm:
  rules:
    - when: never
