.terraform-common:
  variables:
    IGNORED_CVES_YQ_PATH: iac.terraform
    TRIVY_SCAN_REPORT_NAME_PREFIX: terraform
    TRIVY_SCAN_REPORT_NAME: ${TRIVY_SCAN_REPORT_NAME_PREFIX}_${TRIVY_SCAN_REPORT_NAME_SUFFIX}
    SCAN_TYPE: config
    CONFIG_TYPE: ${TRIVY_SCAN_REPORT_NAME_PREFIX}
  cache:
    key: terraform
    when: always
    policy: pull-push
    paths:
      - ${PROJECT_PATH}/**/.terraform
      - ${PROJECT_PATH}/.cache
      - ${PROJECT_PATH}/.terraform.lock.hcl

.terraform-workflow-rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ $MASTER_BRANCH_REGEX && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true"))'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE =~ /^(web|api)$/ && ($WORKFLOW == "full-pipeline" || $WORKFLOW == "build" || $WORKFLOW == "check" || $WORKFLOW == "lint")'
      exists:
        - ${PROJECT_PATH}/main.tf
    - when: never

.terraform-scan-rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ $MASTER_BRANCH_REGEX && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true"))'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE =~ /^(web|api)$/ && $WORKFLOW == "full-pipeline"'
      exists:
        - ${PROJECT_PATH}/main.tf
    - when: never

.terraform-module-test-rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ $MASTER_BRANCH_REGEX && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == "true"))'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      exists:
        - ${PROJECT_PATH}/main.tf
    - if: '$CI_PIPELINE_SOURCE =~ /^(web|api)$/ && $WORKFLOW == "full-pipeline"'
      exists:
        - ${PROJECT_PATH}/main.tf
    - when: never

Terraform:Init:
  stage: init
  extends:
    - .terraform-common
    - .terraform-workflow-rules
  script:
    - terraform init -input=false -no-color -backend-config="workspace_key_prefix=${CI_PROJECT_PATH_SLUG}/${TF_STATE_NAME}" -reconfigure
  needs:
    - job: Common:Init
      artifacts: false
      optional: true

Terraform:Validate:
  stage: lint
  extends:
    - .terraform-common
    - .lint-workflow-rules
  script:
    - terraform validate
    - terraform fmt -recursive -check .
  needs:
    - job: Terraform:Init
      artifacts: false
      optional: false

Terraform:Lint:
  stage: lint
  extends:
    - .lint-workflow-rules
  script:
    - tflint --chdir . --recursive --filter=tests/** --call-module-type=all
  needs:
    - job: Terraform:Init
      artifacts: false
      optional: false

Terraform:Check:README:
  extends:
    - .check-job-common
    - .lint-workflow-rules
  script:
    - |
      if [[ -d modules ]]; then
        for DIR in modules/*; do
          README_FILE=${DIR}/${TF_README_FILE_NAME}
          MD5_TF_DOCS=$(md5sum ${README_FILE})
          terraform-docs markdown table ${DIR} --output-file ${TF_README_FILE_NAME} --required
          MD5_NEW_TF_DOCS=$(md5sum ${README_FILE})

          if [[ ${MD5_TF_DOCS} != ${MD5_NEW_TF_DOCS} ]]; then
            echo "MD5 checksums do not match for ${TF_README_FILE_NAME} file in directory ${DIR}. perform \`terraform-docs markdown table . --output-file ${TF_README_FILE_NAME} --recursive --required\` from project root"
            exit 1
          fi
        done
      fi
    - README_FILE=./${TF_README_FILE_NAME}
    - MD5_TF_DOCS=$(md5sum ${README_FILE})
    - terraform-docs markdown table . --output-file ${README_FILE} --required
    - MD5_NEW_TF_DOCS=$(md5sum ${README_FILE})
    - |
      if [[ ${MD5_TF_DOCS} != ${MD5_NEW_TF_DOCS} ]]; then
        echo "MD5 checksums do not match for ${TF_README_FILE_NAME} file. perform \`terraform-docs markdown table . --output-file ${TF_README_FILE_NAME} --recursive --required\` from project root"
        exit 1
      fi
  needs:
    - job: Common:Init
      artifacts: false
      optional: true

Terraform:Scan:
  extends:
    - .scan-script
    - .terraform-common
    - .terraform-scan-rules
  cache:
    - key: terraform
      when: always
      policy: pull-push
      paths:
        - ${PROJECT_PATH}/**/.terraform
        - ${PROJECT_PATH}/.cache
        - ${PROJECT_PATH}/.terraform.lock.hcl
    - key: trivy-db
      when: always
      policy: pull
      paths:
        - ${CI_PROJECT_DIR}/.trivycache
  needs:
    - job: Terraform:Validate
      artifacts: false
      optional: false
    - job: Trivy:Cache:Warm
      artifacts: false
      optional: true
  artifacts:
    name: Terraform Scan Report
    expose_as: Terraform Scan Report
    when: always
    expire_in: 1 week
    paths:
      - ${PROJECT_PATH}/${TRIVY_SCAN_REPORT_NAME}.junit
      - ${PROJECT_PATH}/${TRIVY_SCAN_REPORT_NAME}.md
      - ${PROJECT_PATH}/${TRIVY_SCAN_REPORT_NAME}.json
      - ${PROJECT_PATH}/${TF_CVE_INFO_FILE_NAME}
    reports:
      junit: ${PROJECT_PATH}/${TRIVY_SCAN_REPORT_NAME}.junit
