.python-common:
  stage: prepare
  variables:
    UV_CACHE_DIR: ${CI_PROJECT_DIR}/${PROJECT_PATH}/.uv
    UV_VENV_RELOCATABLE: "1"
  cache:
    key: ${PROJECT_CACHE_KEY}
    when: always
    policy: pull
    paths:
      - ${PROJECT_PATH}/.uv
  needs:
    - job: Common:Init
      artifacts: true
      optional: true

.python-lint-common:
  needs:
    - job: Python:Dependency:Download
      artifacts: false
      optional: true

.Python:Project:Version:Init:
  stage: .pre
  extends:
    - .lifecycle-rules
  script:
    - echo RELEASE_VERSION=$(cat pyproject.toml | grep '^version *= *"' | head -n1 | sed -E 's/^version *= *"([^"]+)"$/\1/') 2>&1 | tee -a version.env
  artifacts:
    name: Env File
    expose_as: Env File
    when: always
    expire_in: 1 week
    paths:
      - ${PROJECT_PATH}/version.env
    reports:
      dotenv: ${PROJECT_PATH}/version.env

.Python:12:
  image:
    name: ${PYTHON_312_BUILD_IMAGE_REPO}:${PYTHON_312_BUILD_IMAGE_TAG}
    entrypoint: [""]
  extends:
    - .python-common

.Python:Dependency:Download:
  stage: prepare
  extends:
    - .build-test-rules
  cache:
    policy: pull-push
  script:
    - uv sync --frozen --no-install-project --no-install-workspace

.Python:Build:
  stage: build
  extends:
    - .build-test-rules
  cache:
    policy: pull
  script:
    - uv build --offline
  artifacts:
    name: Python Dist
    expose_as: Python Dist
    when: always
    expire_in: 1 week
    paths:
      - ${PROJECT_PATH}/dist/
  needs:
    - job: Common:Init
      artifacts: true
      optional: true
    - job: Python:Dependency:Download
      artifacts: false
      optional: false

Python:Lint:Ruff:
  stage: lint
  extends:
    - .Python:12
    - .python-lint-common
    - .lint-workflow-rules
  script:
    - ruff check --extend-exclude .venv,.uv ${PROJECT_PATH}

Python:Lint:MyPy:
  stage: lint
  extends:
    - .Python:12
    - .python-lint-common
    - .lint-workflow-rules
  script:
    - mypy --exclude '(\.venv|\.uv)' ${PROJECT_PATH}

Python:Lint:ISort:
  stage: lint
  extends:
    - .Python:12
    - .python-lint-common
    - .lint-workflow-rules
  script:
    - isort --extend-skip .venv --extend-skip .uv ${PROJECT_PATH}
    - |
      if [ -n "$(git --no-pager diff)" ]; then
        echo "Please run 'isort .' locally and push the changes"
        exit 1
      else
        echo "isort check passed successfully."
      fi

Python:Lint:PyCodeStyle:
  stage: lint
  extends:
    - .Python:12
    - .python-lint-common
    - .lint-workflow-rules
  script:
    - pycodestyle --exclude=.venv,.uv --show-source ${PROJECT_PATH}

.Python:Test:Unit:
  stage: test
  extends:
    - .build-test-rules
  cache:
    policy: pull
  needs:
    - job: Common:Init
      artifacts: true
      optional: true
    - job: Python:Dependency:Download
      artifacts: false
      optional: false
  artifacts:
    name: Unit Test Report
    expose_as: Unit Test Report
    when: always
    expire_in: 1 week
    paths:
      - ${TEST_REPORT_DIR}/
    reports:
      junit: ${TEST_REPORT_DIR}/junit.xml
